# Generated by Django 3.2.3 on 2021-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_visit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='point',
        ),
        migrations.AddField(
            model_name='collector',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
