# Generated by Django 3.2.3 on 2021-05-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210529_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collector',
            old_name='contact',
            new_name='collector_contact',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='collector',
            new_name='visit_collector',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='user',
            new_name='visit_user',
        ),
    ]
