# Generated by Django 3.2.3 on 2021-05-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210529_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='type',
            field=models.CharField(blank=True, choices=[('all', 'Общего назначения'), ('plastic', 'Для пластика'), ('glass', 'Для стекла'), ('paper', 'Для бумаги'), ('batteries', 'Для батареек')], max_length=100, null=True),
        ),
    ]
