# Generated by Django 3.2.3 on 2021-05-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_visitachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitachievement',
            name='date',
        ),
    ]
