# Generated by Django 3.2.3 on 2021-05-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_visitachievement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
