# Generated by Django 3.2.3 on 2021-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_collector_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=30, null=True)),
                ('short_description', models.TextField(max_length=400)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
