# Generated by Django 3.2.3 on 2021-05-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='if_offline',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
