# Generated by Django 3.2.3 on 2021-05-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_collector_if_offline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collector',
            old_name='if_offline',
            new_name='is_offline',
        ),
    ]
