# Generated by Django 3.2.3 on 2021-05-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_if_offline_collector_is_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visit_achievements',
            field=models.ManyToManyField(blank=True, to='core.VisitAchievement'),
        ),
    ]
