# Generated by Django 3.2.3 on 2021-05-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_visit_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='user_visit_achivements', to='core.VisitAchievement'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('visit_amount', models.IntegerField()),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collector')),
            ],
        ),
    ]
