# Generated by Django 3.2.3 on 2021-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210530_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='user_visit_achivements', to='core.Achievement'),
        ),
    ]
